package sec2;

public class UserException {
	public static void main(String[] args) {
		method1();
	}
	public static void method1(){
		try {
			throw new RunException("사용자 예외");
		} catch (RunException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
